### ISSUE TITLE
Unable to create volume

### ISSUE THREAD

**Issue by chrisk700** [civo/kube100#69]
### Web
Error: "The network_id supplied was empty"

HTTP POST 
```
  authenticity_token: <snip>==
  instance_id: 
  name: VOL1
  size_gb: 1
  attach: on
```

Response:
 ` {"error":"The network_id supplied was empty","code":"parameter_network_id_invalid"}`

### CLI
```
❯ civo version
Civo CLI v0.7.13

❯ civo volume create VOL2 -s 1
Error: UnknownError
```
